// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2CM3GLFkP0MngR7xQ2XwLj7r0e9oynmw',
    appId: '1:167263235132:web:489655201da69c0947e739',
    messagingSenderId: '167263235132',
    projectId: 'brave-system-fb62b',
    authDomain: 'brave-system-fb62b.firebaseapp.com',
    storageBucket: 'brave-system-fb62b.appspot.com',
    measurementId: 'G-0DG2Y2KJTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tjYcIafOz-05IuzqvAHOvakxYl_qMVY',
    appId: '1:167263235132:android:9d9d3eb51ec5be9847e739',
    messagingSenderId: '167263235132',
    projectId: 'brave-system-fb62b',
    storageBucket: 'brave-system-fb62b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEa2mM79g_rPRbZg8767IyOrzwnM8ljzQ',
    appId: '1:167263235132:ios:68c736ab79c9a79f47e739',
    messagingSenderId: '167263235132',
    projectId: 'brave-system-fb62b',
    storageBucket: 'brave-system-fb62b.appspot.com',
    iosClientId: '167263235132-6up37epv5r2hpa3rjdv4lii54dldhva1.apps.googleusercontent.com',
    iosBundleId: 'com.brave.www.bravesystem',
  );
}
